### ISSUE TITLE
npm  update  npm 升级后出错了!!（额外的问题）

### ISSUE THREAD

**Issue by mingming-github** [zce/dashboard#1]
汪老师，我在用npm  update  npm这个指令升级后出现了如下的错误，网上找了很多方法也解决不了，忽然就想到了你，特地请教一下。

在cmd输入指令后不起作用了！！出现下面的错误提示。请问有遇到过吗？
module.js:338
throw err;
^

Error: Cannot find module 'npmlog'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:286:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at C:\Users\Cedon\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:18:11
at Object. (C:\Users\Cedon\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:75:3)
at Module._compile (module.js:434:26)
at Object.Module._extensions..js (module.js:452:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)

**Comment by zce** [comment]
就是更新过程中网络不稳定导致包没下载完全，删了，try once again

**Comment by zce** [comment]
建议在使用npm时选择淘宝的镜像源

**Comment by mingming-github** [comment]
嗯 ，我将其他node版本里面的npm拷贝到这个有问题的node版本里，发现能用了。

**Comment by zce** [comment]
ok
