### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by includeleec** [zce/dashboard#4]
我把dashboard clone下来了。
npm install 了一把，npm run dev后有报错。

```
 ERROR  Failed to compile with 6 errors                                                                                             10:09:09

 error  in ./app/assets/styles/main.scss

Module build failed: Error: ENOENT: no such file or directory, scandir 'E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\vendor'
    at Object.fs.readdirSync (fs.js:913:18)
    at Object.getInstalledBinaries (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\extensions.js:123:13)
    at foundBinariesList (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:45:5)
    at module.exports (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\0-VUE-Study\dashboard\node_modules\.6.0.3@sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

 @ ./app/assets/styles/main.scss 4:14-165 13:3-17:5 14:22-173
 @ ./app/main.js
 @ multi ./task/dev-client ./app/main.js

 error  in ./app/views/login.vue

Module build failed: Error: ENOENT: no such file or directory, scandir 'E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\vendor'
    at Object.fs.readdirSync (fs.js:913:18)
    at Object.getInstalledBinaries (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\extensions.js:123:13)
    at foundBinariesList (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:45:5)
    at module.exports (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\0-VUE-Study\dashboard\node_modules\.6.0.3@sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

 @ ./~/.2.0.5@vue-style-loader!./~/.0.28.0@css-loader?{"minimize":false,"sourceMap":true}!./~/.11.3.4@vue-loader/lib/style-compiler?{"id":"data-v-7e5789fe","scoped":false,"hasInlineConfig":false}!./~/.6.0.3@sass-loader/lib/loader.js?{"sourceMap":true}!./~/.11.3.4@vue-loader/lib/selector.js?type=styles&index=0!./app/views/login.vue 4:14-410 13:3-17:5 14:22-418
 @ ./app/views/login.vue
 @ ./app/libraries/router/routes.js
 @ ./app/libraries/router/index.js
 @ ./app/main.js
 @ multi ./task/dev-client ./app/main.js

 error  in ./app/views/error.vue

Module build failed: Error: ENOENT: no such file or directory, scandir 'E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\vendor'
    at Object.fs.readdirSync (fs.js:913:18)
    at Object.getInstalledBinaries (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\extensions.js:123:13)
    at foundBinariesList (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:45:5)
    at module.exports (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\0-VUE-Study\dashboard\node_modules\.6.0.3@sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

 @ ./~/.2.0.5@vue-style-loader!./~/.0.28.0@css-loader?{"minimize":false,"sourceMap":true}!./~/.11.3.4@vue-loader/lib/style-compiler?{"id":"data-v-3af2b620","scoped":false,"hasInlineConfig":false}!./~/.6.0.3@sass-loader/lib/loader.js?{"sourceMap":true}!./~/.11.3.4@vue-loader/lib/selector.js?type=styles&index=0!./app/views/error.vue 4:14-410 13:3-17:5 14:22-418
 @ ./app/views/error.vue
 @ ./app/libraries/router/routes.js
 @ ./app/libraries/router/index.js
 @ ./app/main.js
 @ multi ./task/dev-client ./app/main.js

 error  in ./app/views/main/profile.vue

Module build failed: Error: ENOENT: no such file or directory, scandir 'E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\vendor'
    at Object.fs.readdirSync (fs.js:913:18)
    at Object.getInstalledBinaries (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\extensions.js:123:13)
    at foundBinariesList (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:45:5)
    at module.exports (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\0-VUE-Study\dashboard\node_modules\.6.0.3@sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

 @ ./~/.2.0.5@vue-style-loader!./~/.0.28.0@css-loader?{"minimize":false,"sourceMap":true}!./~/.11.3.4@vue-loader/lib/style-compiler?{"id":"data-v-25802eeb","scoped":false,"hasInlineConfig":false}!./~/.6.0.3@sass-loader/lib/loader.js?{"sourceMap":true}!./~/.11.3.4@vue-loader/lib/selector.js?type=styles&index=0!./app/views/main/profile.vue 4:14-424 13:3-17:5 14:22-432
 @ ./app/views/main/profile.vue
 @ ./app/libraries/router/main-routes.js
 @ ./app/libraries/router/routes.js
 @ ./app/libraries/router/index.js
 @ ./app/main.js
 @ multi ./task/dev-client ./app/main.js

 error  in ./app/views/main/users.vue

Module build failed: Error: ENOENT: no such file or directory, scandir 'E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\vendor'
    at Object.fs.readdirSync (fs.js:913:18)
    at Object.getInstalledBinaries (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\extensions.js:123:13)
    at foundBinariesList (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:45:5)
    at module.exports (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\0-VUE-Study\dashboard\node_modules\.6.0.3@sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

 @ ./~/.2.0.5@vue-style-loader!./~/.0.28.0@css-loader?{"minimize":false,"sourceMap":true}!./~/.11.3.4@vue-loader/lib/style-compiler?{"id":"data-v-8d52a36c","scoped":false,"hasInlineConfig":false}!./~/.6.0.3@sass-loader/lib/loader.js?{"sourceMap":true}!./~/.11.3.4@vue-loader/lib/selector.js?type=styles&index=0!./app/views/main/users.vue 4:14-422 13:3-17:5 14:22-430
 @ ./app/views/main/users.vue
 @ ./app/libraries/router/main-routes.js
 @ ./app/libraries/router/routes.js
 @ ./app/libraries/router/index.js
 @ ./app/main.js
 @ multi ./task/dev-client ./app/main.js

 error  in ./app/views/demo/components/button.vue

Module build failed: Error: ENOENT: no such file or directory, scandir 'E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\vendor'
    at Object.fs.readdirSync (fs.js:913:18)
    at Object.getInstalledBinaries (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\extensions.js:123:13)
    at foundBinariesList (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:20:15)
    at foundBinaries (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:15:5)
    at Object.module.exports.missingBinary (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\errors.js:45:5)
    at module.exports (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\binding.js:15:30)
    at Object.<anonymous> (E:\0-VUE-Study\dashboard\node_modules\.4.5.2@node-sass\lib\index.js:14:35)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (E:\0-VUE-Study\dashboard\node_modules\.6.0.3@sass-loader\lib\loader.js:3:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)

 @ ./~/.2.0.5@vue-style-loader!./~/.0.28.0@css-loader?{"minimize":false,"sourceMap":true}!./~/.11.3.4@vue-loader/lib/style-compiler?{"id":"data-v-465f9692","scoped":false,"hasInlineConfig":false}!./~/.6.0.3@sass-loader/lib/loader.js?{"sourceMap":true}!./~/.11.3.4@vue-loader/lib/selector.js?type=styles&index=0!./app/views/demo/components/button.vue 4:14-435 13:3-17:5 14:22-443
 @ ./app/views/demo/components/button.vue
 @ ./app/libraries/router/demo-routes.js
 @ ./app/libraries/router/main-routes.js
 @ ./app/libraries/router/routes.js
 @ ./app/libraries/router/index.js
 @ ./app/main.js
 @ multi ./task/dev-client ./app/main.js

> Listening at http://localhost:2017/
```

**Comment by zce** [comment]
重新执行一下 

```bash
$ npm install
```

确保不要报错（机器需要有C++编译环境）

**Comment by zce** [comment]
ping @includeleec
